version: 2.1
orbs:
  python: circleci/python@1.2
  docker: circleci/docker@1.7.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest


  build-push-image-DockerHub:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - setup_remote_docker
      - run:
          name : Build docker image
          command: |
              docker build -t akfio/oc-lettings-8 .
      - deploy:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push akfio/oc-lettings-8



  deploy-to-Heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push web -a oc-lettings-8
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web -a=oc-lettings-8
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku stack:set heroku-20 -a=oc-lettings-8
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set SECRET_KEY="d@n%u@98tun=@j188g25b8ynh1dqto-v%81))gxbbmu$=dy_*)" -a=oc-lettings-8
            git push heroku master


workflows:
  workflow:
    jobs:
      - build-and-test
      - build-push-image-DockerHub:
            requires:
                - build-and-test
            filters:
              branches:
                only: master
      - deploy-to-Heroku:
            requires:
              - build-push-image-DockerHub
            filters:
              branches:
                only: master