version: 2.1
orbs:
  python: circleci/python@1.2
  docker: circleci/docker@1.7.0
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: linting PEP8
          command: flake8


  build-push-image-DockerHub:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - setup_remote_docker
      - run:
          name : Build docker image
          command: |
              docker build -t $DOCKER_LOGIN/oc-lettings-8:$CIRCLE_SHA1 .
      - deploy:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_LOGIN/oc-lettings-8:$CIRCLE_SHA1
            docker tag $DOCKER_LOGIN/oc-lettings-8:$CIRCLE_SHA1 $DOCKER_LOGIN/oc-lettings-8:latest
            docker push $DOCKER_LOGIN/oc-lettings-8:latest


 deploy-to-Heroku:
   executor: heroku/default
   steps:
     - checkout
     - heroku/install
     - run: heroku maintenance:on --app $HEROKU_APP_NAME
     - run: heroku config:set BUILD_NUMBER=$CIRCLE_BUILD_NUM -a $HEROKU_APP_NAME
     - run: heroku config:set SECRET_KEY=$SECRET_KEY -a $HEROKU_APP_NAME
     - run: heroku config:set SENTRY_SDK_DSN=$SENTRY_SDK_DSN -a $HEROKU_APP_NAME
     - run: heroku stack:set heroku-20 -a $HEROKU_APP_NAME
     - run: heroku maintenance:off --app $HEROKU_APP_NAME
     - heroku/deploy-via-git:
         force: true


workflows:
  workflow:
    jobs:
      - build-and-test
      - build-push-image-DockerHub:
            requires:
                - build-and-test
            filters:
              branches:
                only: master
      - deploy-to-Heroku:
            requires:
              - build-push-image-DockerHub
            filters:
              branches:
                only: master